export const TEXT = {
	en: {
		Confirm: "Confirm",
		Browse: "Browse",
		All: "All",
		Update: "Update",
		Install: "Install",
		Loading: "Loading",
		Skip: "Skip",
		Search: "Search...",
		Items: "Items",
		Cancel: "Cancel",
		Select: "Select",
		Tutorials: "Tutorials",
		Next: "Next",
		Prev: "Prev",
		Settings: "Settings",
		Category: "Category",
		Downloads: "Downloads",
		Installed: "Installed",
		Warning1: "AI has been used to translate to this language. There may be some mistakes.",
		Warning2: "Some UI elements might not be aligned properly in this language.",
		Language: "Language",
		Current: "English",
		Flag: "https://flagsapi.com/GB/flat/64.png",
		Change: "Change language to ",
		SelectLang: "Select a language",
		BFR: "Report bugs or request a feature",
		Languages: {
			cn: "Chinese (Simplified)",
			en: "English",
			ru: "Russian",
			jp: "Japanese",
			kr: "Korean",
		},
		_Toasts: {
			ModsLoaded: "Mods Loaded Successfully",
			ApplyingChanges: "Applying changes...",
			InvalidConfig: "Invalid config file",
			ConfigExported: "Config exported!",
			ErrorExporting: "Error exporting config",
			SuccessPort: "Successfully ported old config!",
			GameConfigMismatch: "Game configuration mismatch!",
			ConfigLoaded: "Configuration loaded successfully!",
			ErrDownload: "Error validating mod download",
			DownloadComplete: "Download complete",
			Deleted: "Deleted successfully!",
			ErrOcc: "An error occurred.",
			ImgSaved: "Preview image saved!",
			PresetApplied: "Preset applied!",
			NewUpdates: "<new/> new update(s) available!",
		},
		_Help: {
			SwitchGames: {
				title: "Switching Games",
				content: ["Click on the game icon [top-left] to show the game selection menu."],
			},
			ToggleMods: {
				title: "Toggling Mods",
				content: ["Right click on a mod to enable/disable it."],
			},
			DeleteMod: {
				title: "Deleting Mods",
				content: ["Click on the ✕ to delete the mod."],
			},
			EditModInfo: {
				title: "Editing Mod Details",
				content: ["Select a mod, and edit details such as name, category, source (URL)."],
			},
			ChangeImg: {
				title: "Changing Preview Image",
				content: [
					"Select a mod, click on the edit icon in the right sidebar.",
					"Select an image to use as the preview image for the mod.",
					"Done!",
				],
			},
			OpenExp: {
				title: "Opening a Mod in Explorer",
				content: ["Click on the ↗ icon to open the mod's location in your file explorer."],
			},
			PasteLink: {
				title: "Paste & Open a Link",
				content: ["Copy mod link from Gamebanana", "Paste the link anywhere.", "Mod opens in online mode!"],
			},
			OpenLink: {
				title: "Open a Link from Mod Details",
				content: ["Click on the 🔗 icon to open the mod link in online mode."],
			},
			OnlineMode: {
				title: "Switching to Online Mode",
				content: ["Switch between online and installed modes using the toggle in the left sidebar."],
			},
			UsingPresets: {
				title: "Using Presets",
				content: [
					"Enable the mods that you want to include in the preset.",
					"Click on the '＋ New' button in the left sidebar.",
					"Change presets with just a click!",
				],
			},
			SearchMods: {
				title: "Searching Mods",
				content: ["Start typing anywhere to search for mods. Works both in online and installed mode."],
			},
			DLMods: {
				title: "Downloading & Installing Mods",
				content: [
					"Click on 'Install' and select an option.",
					"Mod will be added to the download queue.",
					"Automatically unzips and installs the mod in the mods folder, along with the preview image.",
				],
			},
			UpdateMods: {
				title: "Updating Mods",
				content: ["Get notified when an installed mod has updates available!"],
			},
			Restore: {
				title: "Restore Points",
				content: ["Create and manage restore points (backup).", "Restore your mods from a saved point."],
			},
			Settings: {
				title: "Settings",
				content: [
					"Change Global/IMM settings.",
					"Configure game specific settings: WuWa",
					"Configure game specific settings: Z·Z·Z",
				],
			},
			Updater: {
				title: "IMM Updater",
				content: ["Update IMM to the latest version from within the app."],
			},
		},
		_Changes: {
			ConfirmChanges: "Confirm changes",
			CreateRestore: "Create a restore point before applying changes",
		},
		_Checklist: {
			Greeting: "Hello, ",
			Configure: "Let's configure some basic settings",
			Continue: "Click Anywhere To Continue",
			ConfirmDir: "Confirm Your Mod Directory",
			NotFound: "We couldn't find your Mod Directory",
			ModsIn: "Mods are stored in {game}MI\\Mods",
		},
		_LeftSideBar: {
			_components: {
				_Downloads: {
					Queue: "Queue",
					Downloading: "Downloading",
					Downloaded: "Downloaded",
					NoQ: "No downloads in queue",
					Clear: "Clear Completed",
				},
				_Restore: {
					Restore: "Restore",
					RestorePoints: "Restore Points",
					CreateRestorePoint: "Create Restore Point",
					RestorePointContent: "Restore Point Content",
					Restricted: "Restricted during Tutorial Mode",
					PleaseSelect: "Please select a valid restore point.",
				},
				_Settings: {
					Global: " Global",
					Change: "Change",
					AutoReload: "Auto Reload",
					_AutoReload: {
						Disable: "Disable",
						Enable: "Enable",
						OnFocus: "On Focus",
						DisableMsg: "Auto Reload Disabled",
						WWMMMsg: "Reload when IMM is focused ★",
						FocusMsg: "Reload when the Game is focused",
						ReloadMsg: "Please reload manually once on changing this.",
					},
					Toggle: "Toggle Mods",
					_Toggle: {
						LeftClick: "Left Click",
						RightClick: "Right Click",
					},
					NSFW: "Online NSFW Content",
					_NSFW: {
						Remove: "Remove",
						Blur: "Blur",
						Show: "Show",
						RemoveMsg: "Filter out all NSFW content",
						BlurMsg: "Click to unblur NSFW content ★",
						ShowMsg: "Do not blur NSFW content",
					},
					WindowBGOpacity: "Window Background Opacity",
					BgType: "Background Type",
					_BgType: { Blank: "Blank", Static: "Static", Dynamic: "Dynamic" },
					WindowType: "Window Type",
					_WindowType: { Windowed: "Windowed", Borderless: "Borderless", Fullscreen: "Fullscreen" },
					ImportExport: "Import/Export Config",
					_ImportExport: {
						ImportPop: "Select config file to import",
						ExportPop: "Export Config",
						Import: "Import",
						Export: "Export",
					},
					Folders: "<game> and Mods Folder",
					LaunchGame: "Launch Game",
					_LaunchGame: { LaunchMsg1: "Launches the game via XXMI", LaunchMsg2: "when you start IMM" },
					HotKey: "Hotkey",
					_HotKey: {
						HKMsg1: "Works only when auto-reload is",
						HKMsg2: "set to",
						HKMsg3: "or",
						HKMsg4: "Avoid using common shortcuts",
						HKMsg5: "such as",
						HKMsg6: "etc...",
						ClearHK: "Clear Hotkey",
						HKEmpty: "Create a preset to set hotkeys.",
					},
				},
			},
			_Left: {
				Mode: "Mode",
				Online: "Online",
			},
			_LeftLocal: {
				Filter: "Filter",
				_Filter: {
					Enabled: "Enabled",
					Disabled: "Disabled",
				},
				Presets: "Presets",
				_Presets: {
					DisableAll: "Disable All Mods",
					Empty: "It's lonely here, create a preset!",
					New: "New",
					Save: "Save",
				},
			},
			_LeftOnline: {
				Type: "Type",
			},
		},
		_Main: {
			_components: {
				_BottomBar: {
					Uncategorized: "Uncategorized",
				},
				_Filter: {
					Show: "Show",
				},
				_TopBar: {
					Most: "Most",
					ModsOnly: "Mods Only",
					Default: "Default",
				},
				_Updater: {
					Downloading: "Downloading",
					InstallNow: "Install Now",
					Error: "Error",
					Retry: "Retry",
					Updater: "IMM Updater",
					CurVer: "Current version",
					Version: "Version",
					ago: "ago",
					Maj: "Major Changes",
					Min: "Minor Changes",
					Patch: "Patches",
					Lat: "You are on the latest version.",
					Soon: "Update will be installed soon",
					In: "Update will be installed in <time>s",
					Use: "You can use the app while updates are being downloaded.",
				},
			},
			_MainLocal: {
				Delete: "Delete",
				Irrev: "This action is irreversible.",
				NoMods: "No mods found in directory",
			},
		},
		_Progress: {
			Close: "Close",
			CreatingRestorePoint: "Creating Restore Point",
			RestorePointCreated: "Restore Point Created",
			RestoringFrom: "Restoring from",
			OperationCancelled: "Operation Cancelled",
			RestorationCompleted: "Restoration Completed",
			RemovingCurrentFiles: "Removing current files",
			DiscoveringFiles: "Discovering files",
			File: "File",
		},
		_RightSideBar: {
			_RightLocal: {
				NoCat: "No such category",
				Source: "Source",
				Notes: "Notes",
				HotKeys: "Hotkeys",
				Key: "Key",
				Action: "Action",
				NoSource: "No source",
				NoNotes: "No notes",
			},
			_RightOnline: {
				Reinstall: "Reinstall",
				Unknown: "Unknown",
				Preview: "Preview Images",
				About: "About",
				LatestUpd: "Latest Update",
				Sep: "Install Separately",
				NoItem: "No item selected",
				LinkCopied: "Link copied to clipboard!",
			},
		},
		_Tutorial: {
			p1: {
				Welcome: "Welcome to",
				Start: "Click anywhere to start the tutorial",
			},
			p2: {
				Title: "How to Toggle & Delete Mods",
				Great: "Great! Now delete the mod by clicking",
				OnTopRight: "on the top right",
				RClick: "Right click on a mod to toggle it on/off",
			},
			p3: {
				Title: "Managing your Mods",
				Rename: "Rename the mod to",
				ClickOn: "Click on",
				PImg: "to change preview image",
				Cat: "Set category to",
			},
			p4: {
				Title1: "Restore & Settings Pages",
				Msg: {
					0: "Open either Restore or Settings Page",
					1: "Great! Now open the Restore Page",
					10: "Great! Now open the Settings Page",
					11: "---",
				},
				Title2: "Going Online",
				ClickAnywhere: "Click anywhere to continue",
			},
			p5: {
				Title: "Browse & Install Mods",
				Switch: "Switch to Online Mode",
				Browse: "Browse Mods from Gamebanana",
				Update: "Update & Install Mods",
			},
			p6: {
				Title: "Installing Mods",
				Direct: "Downloads mod directly in Mods folder",
				Unzip: "Automatically unzips files",
				Preview: "Preview is downloaded",
			},
			p7: {
				Title: "Viewing Mods from a link",
				Copy: "Copy a mod link from Gamebanana",
			},
			p8: {
				Title: "Viewing Mods from a link",
				Paste: "Paste anywhere in the IMM window",
				Opens: "Mod opens in Online Mode",
			},
			p9: {
				Title: "Tutorial Finished!",
				Again1: "You can go through the tutorial again by",
				Again2: "clicking on the App Icon on the top left",
				More: "More interactive tutorials will be added in the future. Stay tuned!",
				End: "Click anywhere to end the tutorial",
			},
			Skip: "SKIP",
		},
	},
	cn: {
		Confirm: "确认",
		Browse: "浏览",
		All: "全部",
		Update: "更新",
		Install: "安装",
		Loading: "加载中",
		Skip: "跳过",
		Search: "搜索...",
		Items: "项目",
		Cancel: "取消",
		Select: "选择",
		Tutorials: "教程",
		Next: "下一步",
		Prev: "上一步",
		Settings: "设置",
		Category: "分类",
		Downloads: "下载",
		Installed: "已安装",
		Warning1: "AI已用于翻译为此语言。可能存在一些错误。",
		Warning2: "某些UI元素在此语言中可能无法正确对齐。",
		Language: "语言",
		Current: "中文",
		Flag: "https://flagsapi.com/CN/flat/64.png",
		Change: "更改语言为 ",
		SelectLang: "选择语言",
		BFR: "报告错误或请求功能",
		Languages: {
			cn: "中文（简体）",
			en: "英语",
			ru: "俄语",
			jp: "日语",
			kr: "韩语",
		},
		_Toasts: {
			ModsLoaded: "模组加载成功",
			ApplyingChanges: "正在应用更改...",
			InvalidConfig: "配置文件无效",
			ConfigExported: "配置已导出！",
			ErrorExporting: "导出配置时出错",
			SuccessPort: "成功移植旧配置！",
			GameConfigMismatch: "游戏配置不匹配！",
			ConfigLoaded: "配置加载成功！",
			ErrDownload: "验证模组下载时出错",
			DownloadComplete: "下载完成",
			Deleted: "删除成功！",
			ErrOcc: "发生错误。",
			ImgSaved: "预览图片已保存！",
			PresetApplied: "预设已应用！",
			NewUpdates: "<new/> 个新更新可用！",
		},
		_Help: {
			SwitchGames: {
				title: "切换游戏",
				content: ["点击游戏图标[左上角]显示游戏选择菜单。"],
			},
			ToggleMods: {
				title: "切换模组",
				content: ["右键点击模组以启用/禁用它。"],
			},
			DeleteMod: {
				title: "删除模组",
				content: ["点击 ✕ 删除模组。"],
			},
			EditModInfo: {
				title: "编辑模组详情",
				content: ["选择一个模组，编辑名称、分类、来源（URL）等详情。"],
			},
			ChangeImg: {
				title: "更改预览图片",
				content: [
					"选择一个模组，点击右侧边栏中的编辑图标。",
					"选择一张图片作为模组的预览图片。",
					"完成！",
				],
			},
			OpenExp: {
				title: "在资源管理器中打开模组",
				content: ["点击 ↗ 图标在文件资源管理器中打开模组位置。"],
			},
			PasteLink: {
				title: "粘贴并打开链接",
				content: ["从 Gamebanana 复制模组链接", "在任意位置粘贴链接。", "模组在在线模式下打开！"],
			},
			OpenLink: {
				title: "从模组详情打开链接",
				content: ["点击 🔗 图标在在线模式下打开模组链接。"],
			},
			OnlineMode: {
				title: "切换到在线模式",
				content: ["使用左侧边栏中的切换按钮在在线模式和已安装模式之间切换。"],
			},
			UsingPresets: {
				title: "使用预设",
				content: [
					"启用您想要包含在预设中的模组。",
					"点击左侧边栏中的'＋ 新建'按钮。",
					"只需点击即可更改预设！",
				],
			},
			SearchMods: {
				title: "搜索模组",
				content: ["在任意位置开始输入以搜索模组。在在线和已安装模式下均可使用。"],
			},
			DLMods: {
				title: "下载和安装模组",
				content: [
					"点击'安装'并选择一个选项。",
					"模组将被添加到下载队列。",
					"自动解压并将模组安装到模组文件夹，同时下载预览图片。",
				],
			},
			UpdateMods: {
				title: "更新模组",
				content: ["当已安装的模组有可用更新时会收到通知！"],
			},
			Restore: {
				title: "还原点",
				content: ["创建和管理还原点（备份）。", "从保存的还原点恢复您的模组。"],
			},
			Settings: {
				title: "设置",
				content: [
					"更改全局/IMM 设置。",
					"配置特定游戏设置：WuWa",
					"配置特定游戏设置：Z·Z·Z",
				],
			},
			Updater: {
				title: "IMM 更新器",
				content: ["在应用内将 IMM 更新到最新版本。"],
			},
		},
		_Changes: {
			ConfirmChanges: "确认更改",
			CreateRestore: "应用更改前创建还原点",
		},
		_Checklist: {
			Greeting: "你好，",
			Configure: "让我们配置一些基本设置",
			Continue: "点击任意处继续",
			ConfirmDir: "确认您的模组目录",
			NotFound: "我们找不到您的模组目录",
			ModsIn: "模组存储在 {game}MI\\Mods",
		},
		_LeftSideBar: {
			_components: {
				_Downloads: {
					Queue: "队列",
					Downloading: "下载中",
					Downloaded: "已下载",
					NoQ: "队列中没有下载",
					Clear: "清除已完成",
				},
				_Restore: {
					Restore: "还原",
					RestorePoints: "还原点",
					CreateRestorePoint: "创建还原点",
					RestorePointContent: "还原点内容",
					Restricted: "教程模式下受限",
					PleaseSelect: "请选择一个有效的还原点。",
				},
				_Settings: {
					Global: " 全局",
					Change: "更改",
					AutoReload: "自动重载",
					_AutoReload: {
						Disable: "禁用",
						Enable: "启用",
						OnFocus: "聚焦时",
						DisableMsg: "自动重载已禁用",
						WWMMMsg: "IMM 获得焦点时重载 ★",
						FocusMsg: "游戏获得焦点时重载",
						ReloadMsg: "更改此设置后请手动重载一次。",
					},
					Toggle: "切换模组",
					_Toggle: {
						LeftClick: "左键点击",
						RightClick: "右键点击",
					},
					NSFW: "在线 NSFW 内容",
					_NSFW: {
						Remove: "移除",
						Blur: "模糊",
						Show: "显示",
						RemoveMsg: "过滤所有 NSFW 内容",
						BlurMsg: "点击取消模糊 NSFW 内容 ★",
						ShowMsg: "不模糊 NSFW 内容",
					},
					WindowBGOpacity: "窗口背景不透明度",
					BgType: "背景类型",
					_BgType: { Blank: "空白", Static: "静态", Dynamic: "动态" },
					WindowType: "窗口类型",
					_WindowType: { Windowed: "窗口化", Borderless: "无边框", Fullscreen: "全屏" },
					ImportExport: "导入/导出配置",
					_ImportExport: {
						ImportPop: "选择要导入的配置文件",
						ExportPop: "导出配置",
						Import: "导入",
						Export: "导出",
					},
					Folders: "<game> 和模组文件夹",
					LaunchGame: "启动游戏",
					_LaunchGame: { LaunchMsg1: "通过 XXMI 启动游戏", LaunchMsg2: "当您启动 IMM 时" },
					HotKey: "热键",
					_HotKey: {
						HKMsg1: "仅在自动重载设置为",
						HKMsg2: "或",
						HKMsg3: "时工作",
						HKMsg4: "避免使用常见快捷键",
						HKMsg5: "例如",
						HKMsg6: "等...",
						ClearHK: "清除热键",
						HKEmpty: "创建预设以设置热键。",
					},
				},
			},
			_Left: {
				Mode: "模式",
				Online: "在线",
			},
			_LeftLocal: {
				Filter: "过滤器",
				_Filter: {
					Enabled: "已启用",
					Disabled: "已禁用",
				},
				Presets: "预设",
				_Presets: {
					DisableAll: "禁用所有模组",
					Empty: "这里很孤单，创建一个预设吧！",
					New: "新建",
					Save: "保存",
				},
			},
			_LeftOnline: {
				Type: "类型",
			},
		},
		_Main: {
			_components: {
				_BottomBar: {
					Uncategorized: "未分类",
				},
				_Filter: {
					Show: "显示",
				},
				_TopBar: {
					Most: "最多",
					ModsOnly: "仅模组",
					Default: "默认",
				},
				_Updater: {
					Downloading: "下载中",
					InstallNow: "立即安装",
					Error: "错误",
					Retry: "重试",
					Updater: "IMM 更新器",
					CurVer: "当前版本",
					Version: "版本",
					ago: "前",
					Maj: "主要更改",
					Min: "次要更改",
					Patch: "补丁",
					Lat: "您使用的是最新版本。",
					Soon: "更新将很快安装",
					In: "更新将在 <time> 秒后安装",
					Use: "您可以在下载更新时使用应用程序。",
				},
			},
			_MainLocal: {
				Delete: "删除",
				Irrev: "此操作不可逆转。",
				NoMods: "目录中未找到模组",
			},
		},
		_Progress: {
			Close: "关闭",
			CreatingRestorePoint: "正在创建还原点",
			RestorePointCreated: "还原点已创建",
			RestoringFrom: "正在从以下位置还原",
			RemovingCurrentFiles: "正在移除当前文件",
			DiscoveringFiles: "正在发现文件",
			OperationCancelled: "操作已取消",
			RestorationCompleted: "还原已完成",
			File: "文件",
		},
		_RightSideBar: {
			_RightLocal: {
				NoCat: "没有此类别",
				Source: "来源",
				Notes: "备注",
				HotKeys: "热键",
				Key: "按键",
				Action: "操作",
				NoSource: "无来源",
				NoNotes: "无备注",
			},
			_RightOnline: {
				Reinstall: "重新安装",
				Unknown: "未知",
				Preview: "预览图片",
				About: "关于",
				LatestUpd: "最新更新",
				Sep: "单独安装",
				NoItem: "未选择项目",
				LinkCopied: "链接已复制到剪贴板！",
			},
		},
		_Tutorial: {
			p1: {
				Welcome: "欢迎来到",
				Start: "点击任意处开始教程",
			},
			p2: {
				Title: "如何切换和删除模组",
				Great: "很好！现在通过点击来删除模组",
				OnTopRight: "在右上角",
				RClick: "右键点击模组以切换开/关",
			},
			p3: {
				Title: "管理您的模组",
				Rename: "将模组重命名为",
				ClickOn: "点击",
				PImg: "更改预览图片",
				Cat: "设置分类为",
			},
			p4: {
				Title1: "还原和设置页面",
				Msg: {
					0: "打开还原或设置页面",
					1: "很好！现在打开还原页面",
					10: "很好！现在打开设置页面",
					11: "---",
				},
				Title2: "上线",
				ClickAnywhere: "点击任意处继续",
			},
			p5: {
				Title: "浏览和安装模组",
				Switch: "切换到在线模式",
				Browse: "从 Gamebanana 浏览模组",
				Update: "更新和安装模组",
			},
			p6: {
				Title: "安装模组",
				Direct: "直接下载模组到模组文件夹",
				Unzip: "自动解压文件",
				Preview: "下载预览图",
			},
			p7: {
				Title: "从链接查看模组",
				Copy: "从 Gamebanana 复制模组链接",
			},
			p8: {
				Title: "从链接查看模组",
				Paste: "在 IMM 窗口的任意位置粘贴",
				Opens: "模组在在线模式下打开",
			},
			p9: {
				Title: "教程完成！",
				Again1: "您可以通过",
				Again2: "点击左上角的应用图标再次进行教程",
				More: "未来将添加更多交互式教程。敬请期待！",
				End: "点击任意处结束教程",
			},
			Skip: "跳过",
		},
	},
	ru: {
		Confirm: "Подтвердить",
		Browse: "Обзор",
		All: "Все",
		Update: "Обновить",
		Install: "Установить",
		Loading: "Загрузка",
		Skip: "Пропустить",
		Search: "Поиск...",
		Items: "Элементы",
		Cancel: "Отмена",
		Select: "Выбрать",
		Tutorials: "Руководства",
		Next: "Далее",
		Prev: "Назад",
		Settings: "Настройки",
		Category: "Категория",
		Downloads: "Загрузки",
		Installed: "Установлено",
		Warning1: "ИИ был использован для перевода на этот язык. Возможны некоторые ошибки.",
		Warning2: "Некоторые элементы интерфейса могут быть неправильно выровнены на этом языке.",
		Language: "Язык",
		Current: "Русский",
		Flag: "https://flagsapi.com/RU/flat/64.png",
		Change: "Изменить язык на ",
		SelectLang: "Выберите язык",
		BFR: "Сообщить об ошибках или запросить функцию",
		Languages: {
			cn: "Китайский (упрощенный)",
			en: "Английский",
			ru: "Русский",
			jp: "Японский",
			kr: "Корейский",
		},
		_Toasts: {
			ModsLoaded: "Моды успешно загружены",
			ApplyingChanges: "Применение изменений...",
			InvalidConfig: "Недействительный файл конфигурации",
			ConfigExported: "Конфигурация экспортирована!",
			ErrorExporting: "Ошибка экспорта конфигурации",
			SuccessPort: "Старая конфигурация успешно перенесена!",
			GameConfigMismatch: "Несоответствие конфигурации игры!",
			ConfigLoaded: "Конфигурация успешно загружена!",
			ErrDownload: "Ошибка проверки загрузки мода",
			DownloadComplete: "Загрузка завершена",
			Deleted: "Успешно удалено!",
			ErrOcc: "Произошла ошибка.",
			ImgSaved: "Превью изображение сохранено!",
			PresetApplied: "Пресет применен!",
			NewUpdates: "<new/> новое(-ых) обновление(-й) доступно!",
		},
		_Help: {
			SwitchGames: {
				title: "Переключение игр",
				content: ["Нажмите на иконку игры [вверху слева], чтобы показать меню выбора игры."],
			},
			ToggleMods: {
				title: "Переключение модов",
				content: ["Щелкните правой кнопкой мыши на мод, чтобы включить/отключить его."],
			},
			DeleteMod: {
				title: "Удаление модов",
				content: ["Нажмите на ✕, чтобы удалить мод."],
			},
			EditModInfo: {
				title: "Редактирование деталей мода",
				content: ["Выберите мод и отредактируйте такие детали, как название, категория, источник (URL)."],
			},
			ChangeImg: {
				title: "Изменение превью изображения",
				content: [
					"Выберите мод, нажмите на иконку редактирования в правой боковой панели.",
					"Выберите изображение для использования в качестве превью для мода.",
					"Готово!",
				],
			},
			OpenExp: {
				title: "Открытие мода в проводнике",
				content: ["Нажмите на иконку ↗, чтобы открыть расположение мода в проводнике файлов."],
			},
			PasteLink: {
				title: "Вставить и открыть ссылку",
				content: ["Скопируйте ссылку на мод с Gamebanana", "Вставьте ссылку в любом месте.", "Мод открывается в онлайн режиме!"],
			},
			OpenLink: {
				title: "Открыть ссылку из деталей мода",
				content: ["Нажмите на иконку 🔗, чтобы открыть ссылку на мод в онлайн режиме."],
			},
			OnlineMode: {
				title: "Переключение в онлайн режим",
				content: ["Переключайтесь между онлайн и установленными режимами с помощью переключателя на левой боковой панели."],
			},
			UsingPresets: {
				title: "Использование пресетов",
				content: [
					"Включите моды, которые вы хотите включить в пресет.",
					"Нажмите на кнопку '＋ Новый' на левой боковой панели.",
					"Меняйте пресеты одним щелчком!",
				],
			},
			SearchMods: {
				title: "Поиск модов",
				content: ["Начните вводить в любом месте для поиска модов. Работает как в онлайн, так и в установленном режиме."],
			},
			DLMods: {
				title: "Загрузка и установка модов",
				content: [
					"Нажмите на 'Установить' и выберите опцию.",
					"Мод будет добавлен в очередь загрузки.",
					"Автоматически распаковывает и устанавливает мод в папку модов вместе с превью изображением.",
				],
			},
			UpdateMods: {
				title: "Обновление модов",
				content: ["Получайте уведомления, когда для установленного мода доступны обновления!"],
			},
			Restore: {
				title: "Точки восстановления",
				content: ["Создавайте и управляйте точками восстановления (резервными копиями).", "Восстанавливайте ваши моды из сохраненной точки."],
			},
			Settings: {
				title: "Настройки",
				content: [
					"Изменение глобальных/IMM настроек.",
					"Настройка параметров для конкретной игры: WuWa",
					"Настройка параметров для конкретной игры: Z·Z·Z",
				],
			},
			Updater: {
				title: "Обновлятор IMM",
				content: ["Обновите IMM до последней версии прямо из приложения."],
			},
		},
		_Changes: {
			ConfirmChanges: "Подтвердить изменения",
			CreateRestore: "Создать точку восстановления перед применением изменений",
		},
		_Checklist: {
			Greeting: "Привет, ",
			Configure: "Давайте настроим основные параметры",
			Continue: "Нажмите в любом месте для продолжения",
			ConfirmDir: "Подтвердите каталог модов",
			NotFound: "Мы не смогли найти ваш каталог модов",
			ModsIn: "Моды хранятся в {game}MI\\Mods",
		},
		_LeftSideBar: {
			_components: {
				_Downloads: {
					Queue: "Очередь",
					Downloading: "Загружается",
					Downloaded: "Загружено",
					NoQ: "Нет загрузок в очереди",
					Clear: "Очистить завершенные",
				},
				_Restore: {
					Restore: "Восстановить",
					RestorePoints: "Точки восстановления",
					CreateRestorePoint: "Создать точку восстановления",
					RestorePointContent: "Содержимое точки восстановления",
					Restricted: "Ограничено в режиме обучения",
					PleaseSelect: "Пожалуйста, выберите действительную точку восстановления.",
				},
				_Settings: {
					Global: " Глобальные",
					Change: "Изменить",
					AutoReload: "Автоперезагрузка",
					_AutoReload: {
						Disable: "Отключить",
						Enable: "Включить",
						OnFocus: "При фокусе",
						DisableMsg: "Автоперезагрузка отключена",
						WWMMMsg: "Перезагружать при фокусе на IMM ★",
						FocusMsg: "Перезагружать при фокусе на игре",
						ReloadMsg: "Пожалуйста, перезагрузите вручную один раз после изменения этого параметра.",
					},
					Toggle: "Переключить моды",
					_Toggle: {
						LeftClick: "Левый клик",
						RightClick: "Правый клик",
					},
					NSFW: "Онлайн NSFW контент",
					_NSFW: {
						Remove: "Удалить",
						Blur: "Размыть",
						Show: "Показать",
						RemoveMsg: "Отфильтровать весь NSFW контент",
						BlurMsg: "Нажмите, чтобы размыть NSFW контент ★",
						ShowMsg: "Не размывать NSFW контент",
					},
					WindowBGOpacity: "Прозрачность фона окна",
					BgType: "Тип фона",
					_BgType: { Blank: "Пустой", Static: "Статичный", Dynamic: "Динамичный" },
					WindowType: "Тип окна",
					_WindowType: { Windowed: "Оконный", Borderless: "Без границ", Fullscreen: "Полноэкранный" },
					ImportExport: "Импорт/Экспорт конфигурации",
					_ImportExport: {
						ImportPop: "Выберите файл конфигурации для импорта",
						ExportPop: "Экспорт конфигурации",
						Import: "Импорт",
						Export: "Экспорт",
					},
					Folders: "<game> и папка модов",
					LaunchGame: "Запустить игру",
					_LaunchGame: { LaunchMsg1: "Запускает игру через XXMI", LaunchMsg2: "при запуске IMM" },
					HotKey: "Горячая клавиша",
					_HotKey: {
						HKMsg1: "Работает только при автоперезагрузке",
						HKMsg2: "установленной на",
						HKMsg3: "или",
						HKMsg4: "Избегайте использования общих сочетаний клавиш",
						HKMsg5: "таких как",
						HKMsg6: "и т.д...",
						ClearHK: "Очистить горячую клавишу",
						HKEmpty: "Создайте пресет для настройки горячих клавиш.",
					},
				},
			},
			_Left: {
				Mode: "Режим",
				Online: "Онлайн",
			},
			_LeftLocal: {
				Filter: "Фильтр",
				_Filter: {
					Enabled: "Включено",
					Disabled: "Отключено",
				},
				Presets: "Пресеты",
				_Presets: {
					DisableAll: "Отключить все моды",
					Empty: "Здесь одиноко, создайте пресет!",
					New: "Новый",
					Save: "Сохранить",
				},
			},
			_LeftOnline: {
				Type: "Тип",
			},
		},
		_Main: {
			_components: {
				_BottomBar: {
					Uncategorized: "Без категории",
				},
				_Filter: {
					Show: "Показать",
				},
				_TopBar: {
					Most: "Больше всего",
					ModsOnly: "Только моды",
					Default: "По умолчанию",
				},
				_Updater: {
					Downloading: "Загружается",
					InstallNow: "Установить сейчас",
					Error: "Ошибка",
					Retry: "Повторить",
					Updater: "Обновлятор IMM",
					CurVer: "Текущая версия",
					Version: "Версия",
					ago: "назад",
					Maj: "Основные изменения",
					Min: "Мелкие изменения",
					Patch: "Исправления",
					Lat: "У вас установлена последняя версия.",
					Soon: "Обновление будет установлено скоро",
					In: "Обновление будет установлено через <time> с",
					Use: "Вы можете использовать приложение во время загрузки обновлений.",
				},
			},
			_MainLocal: {
				Delete: "Удалить",
				Irrev: "Это действие необратимо.",
				NoMods: "Моды не найдены в каталоге",
			},
		},
		_Progress: {
			Close: "Закрыть",
			CreatingRestorePoint: "Создание точки восстановления",
			RestorePointCreated: "Точка восстановления создана",
			RestoringFrom: "Восстановление из",
			RemovingCurrentFiles: "Удаление текущих файлов",
			DiscoveringFiles: "Обнаружение файлов",
			OperationCancelled: "Операция отменена",
			RestorationCompleted: "Восстановление завершено",
			File: "Файл",
		},
		_RightSideBar: {
			_RightLocal: {
				NoCat: "Нет такой категории",
				Source: "Источник",
				Notes: "Заметки",
				HotKeys: "Горячие клавиши",
				Key: "Клавиша",
				Action: "Действие",
				NoSource: "Нет источника",
				NoNotes: "Нет заметок",
			},
			_RightOnline: {
				Reinstall: "Переустановить",
				Unknown: "Неизвестно",
				Preview: "Превью изображения",
				About: "О программе",
				LatestUpd: "Последнее обновление",
				Sep: "Установить отдельно",
				NoItem: "Элемент не выбран",
				LinkCopied: "Ссылка скопирована в буфер обмена!",
			},
		},
		_Tutorial: {
			p1: {
				Welcome: "Добро пожаловать в",
				Start: "Нажмите в любом месте, чтобы начать обучение",
			},
			p2: {
				Title: "Как переключать и удалять моды",
				Great: "Отлично! Теперь удалите мод, нажав",
				OnTopRight: "в правом верхнем углу",
				RClick: "Щелкните правой кнопкой мыши по моду, чтобы включить/выключить его",
			},
			p3: {
				Title: "Управление вашими модами",
				Rename: "Переименуйте мод в",
				ClickOn: "Нажмите на",
				PImg: "чтобы изменить превью изображение",
				Cat: "Установите категорию на",
			},
			p4: {
				Title1: "Страницы восстановления и настроек",
				Msg: {
					0: "Откройте страницу восстановления или настроек",
					1: "Отлично! Теперь откройте страницу восстановления",
					10: "Отлично! Теперь откройте страницу настроек",
					11: "---",
				},
				Title2: "Переход в онлайн",
				ClickAnywhere: "Нажмите в любом месте для продолжения",
			},
			p5: {
				Title: "Просмотр и установка модов",
				Switch: "Переключиться в онлайн режим",
				Browse: "Просматривать моды с Gamebanana",
				Update: "Обновлять и устанавливать моды",
			},
			p6: {
				Title: "Установка модов",
				Direct: "Загружает мод прямо в папку модов",
				Unzip: "Автоматически распаковывает файлы",
				Preview: "Превью загружается",
			},
			p7: {
				Title: "Просмотр модов по ссылке",
				Copy: "Скопируйте ссылку мода с Gamebanana",
			},
			p8: {
				Title: "Просмотр модов по ссылке",
				Paste: "Вставьте в любом месте окна IMM",
				Opens: "Мод открывается в онлайн режиме",
			},
			p9: {
				Title: "Обучение завершено!",
				Again1: "Вы можете пройти обучение снова,",
				Again2: "нажав на иконку приложения в левом верхнем углу",
				More: "В будущем будут добавлены более интерактивные обучающие материалы. Следите за обновлениями!",
				End: "Нажмите в любом месте, чтобы завершить обучение",
			},
			Skip: "ПРОПУСТИТЬ",
		},
	},
	jp: {
		Confirm: "確認",
		Browse: "参照",
		All: "すべて",
		Update: "更新",
		Install: "インストール",
		Loading: "読み込み中",
		Skip: "スキップ",
		Search: "検索...",
		Items: "アイテム",
		Cancel: "キャンセル",
		Select: "選択",
		Tutorials: "チュートリアル",
		Next: "次へ",
		Prev: "前へ",
		Settings: "設定",
		Category: "カテゴリ",
		Downloads: "ダウンロード",
		Installed: "インストール済み",
		Warning1: "この言語への翻訳にAIが使用されました。いくつかの間違いがある可能性があります。",
		Warning2: "一部のUI要素がこの言語では適切に配置されない場合があります。",
		Language: "言語",
		Current: "日本語",
		Flag: "https://flagsapi.com/JP/flat/64.png",
		Change: "言語を変更： ",
		SelectLang: "言語を選択",
		BFR: "バグを報告するか機能をリクエスト",
		Languages: {
			cn: "中国語（簡体字）",
			en: "英語",
			ru: "ロシア語",
			jp: "日本語",
			kr: "韓国語",
		},
		_Toasts: {
			ModsLoaded: "Modが正常に読み込まれました",
			ApplyingChanges: "変更を適用中...",
			InvalidConfig: "無効な設定ファイル",
			ConfigExported: "設定をエクスポートしました！",
			ErrorExporting: "設定のエクスポート中にエラーが発生しました",
			SuccessPort: "古い設定の移行に成功しました！",
			GameConfigMismatch: "ゲーム設定の不一致！",
			ConfigLoaded: "設定が正常に読み込まれました！",
			ErrDownload: "Modダウンロードの検証エラー",
			DownloadComplete: "ダウンロード完了",
			Deleted: "正常に削除されました！",
			ErrOcc: "エラーが発生しました。",
			ImgSaved: "プレビュー画像を保存しました！",
			PresetApplied: "プリセットを適用しました！",
			NewUpdates: "<new/> 件の新しいアップデートが利用可能です！",
		},
		_Help: {
			SwitchGames: {
				title: "ゲームの切り替え",
				content: ["ゲームアイコン[左上]をクリックしてゲーム選択メニューを表示します。"],
			},
			ToggleMods: {
				title: "Modの切り替え",
				content: ["Modを右クリックして有効/無効を切り替えます。"],
			},
			DeleteMod: {
				title: "Modの削除",
				content: ["✕ をクリックしてModを削除します。"],
			},
			EditModInfo: {
				title: "Mod詳細の編集",
				content: ["Modを選択し、名前、カテゴリ、ソース（URL）などの詳細を編集します。"],
			},
			ChangeImg: {
				title: "プレビュー画像の変更",
				content: [
					"Modを選択し、右サイドバーの編集アイコンをクリックします。",
					"Modのプレビュー画像として使用する画像を選択します。",
					"完了！",
				],
			},
			OpenExp: {
				title: "エクスプローラーでModを開く",
				content: ["↗ アイコンをクリックして、ファイルエクスプローラーでModの場所を開きます。"],
			},
			PasteLink: {
				title: "リンクを貼り付けて開く",
				content: ["GamebananaからModリンクをコピー", "リンクをどこかに貼り付けます。", "Modがオンラインモードで開きます！"],
			},
			OpenLink: {
				title: "Mod詳細からリンクを開く",
				content: ["🔗 アイコンをクリックして、オンラインモードでModリンクを開きます。"],
			},
			OnlineMode: {
				title: "オンラインモードへの切り替え",
				content: ["左サイドバーのトグルを使用して、オンラインモードとインストール済みモード間を切り替えます。"],
			},
			UsingPresets: {
				title: "プリセットの使用",
				content: [
					"プリセットに含めたいModを有効にします。",
					"左サイドバーの'＋ 新規'ボタンをクリックします。",
					"クリック一つでプリセットを変更！",
				],
			},
			SearchMods: {
				title: "Modの検索",
				content: ["どこかで入力を開始してModを検索します。オンラインモードとインストール済みモードの両方で機能します。"],
			},
			DLMods: {
				title: "Modのダウンロードとインストール",
				content: [
					"'インストール'をクリックしてオプションを選択します。",
					"Modがダウンロードキューに追加されます。",
					"自動的に解凍し、プレビュー画像と共にModフォルダにインストールします。",
				],
			},
			UpdateMods: {
				title: "Modの更新",
				content: ["インストール済みのModに利用可能なアップデートがある場合に通知を受け取ります！"],
			},
			Restore: {
				title: "復元ポイント",
				content: ["復元ポイント（バックアップ）を作成・管理します。", "保存された復元ポイントからModを復元します。"],
			},
			Settings: {
				title: "設定",
				content: [
					"グローバル/IMM設定を変更します。",
					"ゲーム固有の設定を構成：WuWa",
					"ゲーム固有の設定を構成：Z·Z·Z",
				],
			},
			Updater: {
				title: "IMMアップデーター",
				content: ["アプリ内からIMMを最新バージョンに更新します。"],
			},
		},
		_Changes: {
			ConfirmChanges: "変更を確認",
			CreateRestore: "変更を適用する前に復元ポイントを作成",
		},
		_Checklist: {
			Greeting: "こんにちは、",
			Configure: "基本設定を行いましょう",
			Continue: "どこかをクリックして続行",
			ConfirmDir: "Modディレクトリを確認",
			NotFound: "Modディレクトリが見つかりませんでした",
			ModsIn: "Modは{game}MI\\Modsに保存されます",
		},
		_LeftSideBar: {
			_components: {
				_Downloads: {
					Queue: "キュー",
					Downloading: "ダウンロード中",
					Downloaded: "ダウンロード完了",
					NoQ: "キューにダウンロードがありません",
					Clear: "完了したものをクリア",
				},
				_Restore: {
					Restore: "復元",
					RestorePoints: "復元ポイント",
					CreateRestorePoint: "復元ポイントを作成",
					RestorePointContent: "復元ポイントの内容",
					Restricted: "チュートリアルモードでは制限されています",
					PleaseSelect: "有効な復元ポイントを選択してください。",
				},
				_Settings: {
					Global: " グローバル",
					Change: "変更",
					AutoReload: "自動リロード",
					_AutoReload: {
						Disable: "無効",
						Enable: "有効",
						OnFocus: "フォーカス時",
						DisableMsg: "自動リロードが無効になりました",
						WWMMMsg: "IMMがフォーカスされた時にリロード ★",
						FocusMsg: "ゲームがフォーカスされた時にリロード",
						ReloadMsg: "この設定を変更した後、一度手動でリロードしてください。",
					},
					Toggle: "Modの切り替え",
					_Toggle: {
						LeftClick: "左クリック",
						RightClick: "右クリック",
					},
					NSFW: "オンライン NSFW コンテンツ",
					_NSFW: {
						Remove: "除去",
						Blur: "ぼかし",
						Show: "表示",
						RemoveMsg: "すべてのNSFWコンテンツをフィルタリング",
						BlurMsg: "クリックしてNSFWコンテンツのぼかしを解除 ★",
						ShowMsg: "NSFWコンテンツをぼかさない",
					},
					WindowBGOpacity: "ウィンドウ背景の不透明度",
					BgType: "背景タイプ",
					_BgType: { Blank: "空白", Static: "静的", Dynamic: "動的" },
					WindowType: "ウィンドウタイプ",
					_WindowType: { Windowed: "ウィンドウ", Borderless: "ボーダーレス", Fullscreen: "フルスクリーン" },
					ImportExport: "設定のインポート/エクスポート",
					_ImportExport: {
						ImportPop: "インポートする設定ファイルを選択",
						ExportPop: "設定のエクスポート",
						Import: "インポート",
						Export: "エクスポート",
					},
					Folders: "<game> とModフォルダ",
					LaunchGame: "ゲーム起動",
					_LaunchGame: { LaunchMsg1: "XXMIを介してゲームを起動", LaunchMsg2: "IMMを起動する時" },
					HotKey: "ホットキー",
					_HotKey: {
						HKMsg1: "自動リロードが",
						HKMsg2: "に設定されている時のみ動作",
						HKMsg3: "または",
						HKMsg4: "一般的なショートカットの使用を避ける",
						HKMsg5: "例：",
						HKMsg6: "など...",
						ClearHK: "ホットキーをクリア",
						HKEmpty: "ホットキーを設定するにはプリセットを作成してください。",
					},
				},
			},
			_Left: {
				Mode: "モード",
				Online: "オンライン",
			},
			_LeftLocal: {
				Filter: "フィルター",
				_Filter: {
					Enabled: "有効",
					Disabled: "無効",
				},
				Presets: "プリセット",
				_Presets: {
					DisableAll: "すべてのModを無効化",
					Empty: "寂しいですね、プリセットを作成しましょう！",
					New: "新規",
					Save: "保存",
				},
			},
			_LeftOnline: {
				Type: "タイプ",
			},
		},
		_Main: {
			_components: {
				_BottomBar: {
					Uncategorized: "未分類",
				},
				_Filter: {
					Show: "表示",
				},
				_TopBar: {
					Most: "最多",
					ModsOnly: "Modのみ",
					Default: "デフォルト",
				},
				_Updater: {
					Downloading: "ダウンロード中",
					InstallNow: "今すぐインストール",
					Error: "エラー",
					Retry: "再試行",
					Updater: "IMM アップデーター",
					CurVer: "現在のバージョン",
					Version: "バージョン",
					ago: "前",
					Maj: "主要な変更",
					Min: "軽微な変更",
					Patch: "パッチ",
					Lat: "最新バージョンを使用しています。",
					Soon: "まもなくアップデートがインストールされます",
					In: "<time>秒後にアップデートがインストールされます",
					Use: "アップデートのダウンロード中もアプリケーションを使用できます。",
				},
			},
			_MainLocal: {
				Delete: "削除",
				Irrev: "この操作は元に戻せません。",
				NoMods: "ディレクトリにModが見つかりません",
			},
		},
		_Progress: {
			Close: "閉じる",
			CreatingRestorePoint: "復元ポイントを作成中",
			RestorePointCreated: "復元ポイントが作成されました",
			RestoringFrom: "復元中",
			RemovingCurrentFiles: "現在のファイルを削除中",
			DiscoveringFiles: "ファイルを検出中",
			OperationCancelled: "操作がキャンセルされました",
			RestorationCompleted: "復元が完了しました",
			File: "ファイル",
		},
		_RightSideBar: {
			_RightLocal: {
				NoCat: "そのようなカテゴリはありません",
				Source: "ソース",
				Notes: "ノート",
				HotKeys: "ホットキー",
				Key: "キー",
				Action: "アクション",
				NoSource: "ソースなし",
				NoNotes: "ノートなし",
			},
			_RightOnline: {
				Reinstall: "再インストール",
				Unknown: "不明",
				Preview: "プレビュー画像",
				About: "詳細",
				LatestUpd: "最新アップデート",
				Sep: "個別にインストール",
				NoItem: "アイテムが選択されていません",
				LinkCopied: "リンクをクリップボードにコピーしました！",
			},
		},
		_Tutorial: {
			p1: {
				Welcome: "ようこそ",
				Start: "どこかをクリックしてチュートリアルを開始",
			},
			p2: {
				Title: "Modの切り替えと削除方法",
				Great: "素晴らしい！次にModを削除するには",
				OnTopRight: "右上の",
				RClick: "Modを右クリックしてオン/オフを切り替え",
			},
			p3: {
				Title: "Modの管理",
				Rename: "Modの名前を変更",
				ClickOn: "クリック",
				PImg: "プレビュー画像を変更",
				Cat: "カテゴリを設定",
			},
			p4: {
				Title1: "復元と設定ページ",
				Msg: {
					0: "復元または設定ページを開く",
					1: "素晴らしい！次に復元ページを開く",
					10: "素晴らしい！次に設定ページを開く",
					11: "---",
				},
				Title2: "オンラインに移行",
				ClickAnywhere: "どこかをクリックして続行",
			},
			p5: {
				Title: "Modの閲覧とインストール",
				Switch: "オンラインモードに切り替え",
				Browse: "GamebananaからModを閲覧",
				Update: "Modの更新とインストール",
			},
			p6: {
				Title: "Modのインストール",
				Direct: "Modフォルダに直接ダウンロード",
				Unzip: "ファイルを自動解凍",
				Preview: "プレビューがダウンロードされます",
			},
			p7: {
				Title: "リンクからModを表示",
				Copy: "GamebananaからModリンクをコピー",
			},
			p8: {
				Title: "リンクからModを表示",
				Paste: "IMMウィンドウのどこかに貼り付け",
				Opens: "Modがオンラインモードで開きます",
			},
			p9: {
				Title: "チュートリアル完了！",
				Again1: "チュートリアルをもう一度実行するには",
				Again2: "左上のアプリアイコンをクリック",
				More: "今後、より多くのインタラクティブなチュートリアルが追加される予定です。お楽しみに！",
				End: "どこかをクリックしてチュートリアルを終了",
			},
			Skip: "スキップ",
		},
	},
	kr: {
		Confirm: "확인",
		Browse: "찾아보기",
		All: "모두",
		Update: "업데이트",
		Install: "설치",
		Loading: "로딩 중",
		Skip: "건너뛰기",
		Search: "검색...",
		Items: "항목",
		Cancel: "취소",
		Select: "선택",
		Tutorials: "튜토리얼",
		Next: "다음",
		Prev: "이전",
		Settings: "설정",
		Category: "카테고리",
		Downloads: "다운로드",
		Installed: "설치됨",
		Warning1: "이 언어로의 번역에 AI가 사용되었습니다. 일부 실수가 있을 수 있습니다.",
		Warning2: "일부 UI 요소가 이 언어에서 제대로 정렬되지 않을 수 있습니다.",
		Language: "언어",
		Current: "한국어",
		Flag: "https://flagsapi.com/KR/flat/64.png",
		Change: "언어 변경: ",
		SelectLang: "언어 선택",
		BFR: "버그 신고 또는 기능 요청",
		Languages: {
			cn: "중국어 (간체)",
			en: "영어",
			ru: "러시아어",
			jp: "일본어",
			kr: "한국어",
		},
		_Toasts: {
			ModsLoaded: "모드가 성공적으로 로드되었습니다",
			ApplyingChanges: "변경 사항 적용 중...",
			InvalidConfig: "잘못된 설정 파일",
			ConfigExported: "설정이 내보내졌습니다!",
			ErrorExporting: "설정 내보내기 오류",
			SuccessPort: "이전 설정을 성공적으로 이식했습니다!",
			GameConfigMismatch: "게임 설정 불일치!",
			ConfigLoaded: "설정이 성공적으로 로드되었습니다!",
			ErrDownload: "모드 다운로드 검증 오류",
			DownloadComplete: "다운로드 완료",
			Deleted: "성공적으로 삭제되었습니다!",
			ErrOcc: "오류가 발생했습니다.",
			ImgSaved: "미리보기 이미지가 저장되었습니다!",
			PresetApplied: "프리셋이 적용되었습니다!",
			NewUpdates: "<new/>개의 새로운 업데이트를 사용할 수 있습니다!",
		},
		_Help: {
			SwitchGames: {
				title: "게임 전환",
				content: ["게임 아이콘[좌상단]을 클릭하여 게임 선택 메뉴를 표시합니다."],
			},
			ToggleMods: {
				title: "모드 토글",
				content: ["모드를 오른쪽 클릭하여 활성화/비활성화합니다."],
			},
			DeleteMod: {
				title: "모드 삭제",
				content: ["✕를 클릭하여 모드를 삭제합니다."],
			},
			EditModInfo: {
				title: "모드 세부 정보 편집",
				content: ["모드를 선택하고 이름, 카테고리, 소스(URL) 등의 세부 정보를 편집합니다."],
			},
			ChangeImg: {
				title: "미리보기 이미지 변경",
				content: [
					"모드를 선택하고 오른쪽 사이드바에서 편집 아이콘을 클릭합니다.",
					"모드의 미리보기 이미지로 사용할 이미지를 선택합니다.",
					"완료!",
				],
			},
			OpenExp: {
				title: "탐색기에서 모드 열기",
				content: ["↗ 아이콘을 클릭하여 파일 탐색기에서 모드의 위치를 엽니다."],
			},
			PasteLink: {
				title: "링크 붙여넣기 및 열기",
				content: ["Gamebanana에서 모드 링크 복사", "링크를 아무 곳에나 붙여넣습니다.", "모드가 온라인 모드에서 열립니다!"],
			},
			OpenLink: {
				title: "모드 세부 정보에서 링크 열기",
				content: ["🔗 아이콘을 클릭하여 온라인 모드에서 모드 링크를 엽니다."],
			},
			OnlineMode: {
				title: "온라인 모드로 전환",
				content: ["왼쪽 사이드바의 토글을 사용하여 온라인 모드와 설치된 모드 간에 전환합니다."],
			},
			UsingPresets: {
				title: "프리셋 사용",
				content: [
					"프리셋에 포함하려는 모드를 활성화합니다.",
					"왼쪽 사이드바에서 '＋ 새로 만들기' 버튼을 클릭합니다.",
					"클릭 한 번으로 프리셋을 변경하세요!",
				],
			},
			SearchMods: {
				title: "모드 검색",
				content: ["아무 곳에나 입력을 시작하여 모드를 검색합니다. 온라인 및 설치된 모드 모두에서 작동합니다."],
			},
			DLMods: {
				title: "모드 다운로드 및 설치",
				content: [
					"'설치'를 클릭하고 옵션을 선택합니다.",
					"모드가 다운로드 대기열에 추가됩니다.",
					"자동으로 압축을 풀고 미리보기 이미지와 함께 모드 폴더에 설치합니다.",
				],
			},
			UpdateMods: {
				title: "모드 업데이트",
				content: ["설치된 모드에 사용 가능한 업데이트가 있을 때 알림을 받으세요!"],
			},
			Restore: {
				title: "복원 지점",
				content: ["복원 지점(백업)을 생성하고 관리합니다.", "저장된 복원 지점에서 모드를 복원합니다."],
			},
			Settings: {
				title: "설정",
				content: [
					"글로벌/IMM 설정을 변경합니다.",
					"게임별 설정 구성: WuWa",
					"게임별 설정 구성: Z·Z·Z",
				],
			},
			Updater: {
				title: "IMM 업데이터",
				content: ["앱 내에서 IMM을 최신 버전으로 업데이트합니다."],
			},
		},
		_Changes: {
			ConfirmChanges: "변경 사항 확인",
			CreateRestore: "변경 사항을 적용하기 전에 복원 지점 생성",
		},
		_Checklist: {
			Greeting: "안녕하세요, ",
			Configure: "기본 설정을 구성해 봅시다",
			Continue: "아무 곳이나 클릭하여 계속",
			ConfirmDir: "모드 디렉토리 확인",
			NotFound: "모드 디렉토리를 찾을 수 없습니다",
			ModsIn: "모드는 {game}MI\\Mods에 저장됩니다",
		},
		_LeftSideBar: {
			_components: {
				_Downloads: {
					Queue: "대기열",
					Downloading: "다운로드 중",
					Downloaded: "다운로드 완료",
					NoQ: "대기열에 다운로드가 없습니다",
					Clear: "완료된 항목 정리",
				},
				_Restore: {
					Restore: "복원",
					RestorePoints: "복원 지점",
					CreateRestorePoint: "복원 지점 생성",
					RestorePointContent: "복원 지점 내용",
					Restricted: "튜토리얼 모드에서 제한됨",
					PleaseSelect: "유효한 복원 지점을 선택하세요.",
				},
				_Settings: {
					Global: " 글로벌",
					Change: "변경",
					AutoReload: "자동 새로고침",
					_AutoReload: {
						Disable: "비활성화",
						Enable: "활성화",
						OnFocus: "포커스 시",
						DisableMsg: "자동 새로고침이 비활성화되었습니다",
						WWMMMsg: "IMM이 포커스될 때 새로고침 ★",
						FocusMsg: "게임이 포커스될 때 새로고침",
						ReloadMsg: "이 설정을 변경한 후 한 번 수동으로 새로고침해주세요.",
					},
					Toggle: "모드 토글",
					_Toggle: {
						LeftClick: "왼쪽 클릭",
						RightClick: "오른쪽 클릭",
					},
					NSFW: "온라인 NSFW 콘텐츠",
					_NSFW: {
						Remove: "제거",
						Blur: "흐림",
						Show: "표시",
						RemoveMsg: "모든 NSFW 콘텐츠 필터링",
						BlurMsg: "클릭하여 NSFW 콘텐츠 흐림 해제 ★",
						ShowMsg: "NSFW 콘텐츠를 흐리게 하지 않음",
					},
					WindowBGOpacity: "창 배경 불투명도",
					BgType: "배경 타입",
					_BgType: { Blank: "공백", Static: "정적", Dynamic: "동적" },
					WindowType: "창 타입",
					_WindowType: { Windowed: "창 모드", Borderless: "테두리 없음", Fullscreen: "전체 화면" },
					ImportExport: "설정 가져오기/내보내기",
					_ImportExport: {
						ImportPop: "가져올 설정 파일 선택",
						ExportPop: "설정 내보내기",
						Import: "가져오기",
						Export: "내보내기",
					},
					Folders: "<game> 및 모드 폴더",
					LaunchGame: "게임 실행",
					_LaunchGame: { LaunchMsg1: "XXMI를 통해 게임 실행", LaunchMsg2: "IMM을 시작할 때" },
					HotKey: "단축키",
					_HotKey: {
						HKMsg1: "자동 새로고침이",
						HKMsg2: "로 설정되어 있을 때만 작동",
						HKMsg3: "또는",
						HKMsg4: "일반적인 단축키 사용을 피하세요",
						HKMsg5: "예:",
						HKMsg6: "등...",
						ClearHK: "단축키 지우기",
						HKEmpty: "단축키를 설정하려면 프리셋을 만드세요.",
					},
				},
			},
			_Left: {
				Mode: "모드",
				Online: "온라인",
			},
			_LeftLocal: {
				Filter: "필터",
				_Filter: {
					Enabled: "활성화됨",
					Disabled: "비활성화됨",
				},
				Presets: "프리셋",
				_Presets: {
					DisableAll: "모든 모드 비활성화",
					Empty: "외롭네요, 프리셋을 만들어보세요!",
					New: "새로 만들기",
					Save: "저장",
				},
			},
			_LeftOnline: {
				Type: "타입",
			},
		},
		_Main: {
			_components: {
				_BottomBar: {
					Uncategorized: "분류되지 않음",
				},
				_Filter: {
					Show: "표시",
				},
				_TopBar: {
					Most: "가장 많은",
					ModsOnly: "모드만",
					Default: "기본값",
				},
				_Updater: {
					Downloading: "다운로드 중",
					InstallNow: "지금 설치",
					Error: "오류",
					Retry: "다시 시도",
					Updater: "IMM 업데이터",
					CurVer: "현재 버전",
					Version: "버전",
					ago: "전",
					Maj: "주요 변경 사항",
					Min: "경미한 변경 사항",
					Patch: "패치",
					Lat: "최신 버전을 사용 중입니다.",
					Soon: "곧 업데이트가 설치됩니다",
					In: "<time>초 후에 업데이트가 설치됩니다",
					Use: "업데이트를 다운로드하는 동안 앱을 사용할 수 있습니다.",
				},
			},
			_MainLocal: {
				Delete: "삭제",
				Irrev: "이 작업은 되돌릴 수 없습니다.",
				NoMods: "디렉토리에서 모드를 찾을 수 없습니다",
			},
		},
		_Progress: {
			Close: "닫기",
			CreatingRestorePoint: "복원 지점 생성 중",
			RestorePointCreated: "복원 지점이 생성되었습니다",
			RestoringFrom: "다음에서 복원 중",
			RemovingCurrentFiles: "현재 파일 제거 중",
			DiscoveringFiles: "파일 검색 중",
			OperationCancelled: "작업이 취소되었습니다",
			RestorationCompleted: "복원이 완료되었습니다",
			File: "파일",
		},
		_RightSideBar: {
			_RightLocal: {
				NoCat: "해당 카테고리가 없습니다",
				Source: "소스",
				Notes: "노트",
				HotKeys: "단축키",
				Key: "키",
				Action: "액션",
				NoSource: "소스 없음",
				NoNotes: "노트 없음",
			},
			_RightOnline: {
				Reinstall: "재설치",
				Unknown: "알 수 없음",
				Preview: "미리보기 이미지",
				About: "정보",
				LatestUpd: "최신 업데이트",
				Sep: "개별 설치",
				NoItem: "선택된 항목 없음",
				LinkCopied: "링크가 클립보드에 복사되었습니다!",
			},
		},
		_Tutorial: {
			p1: {
				Welcome: "환영합니다",
				Start: "아무 곳이나 클릭하여 튜토리얼 시작",
			},
			p2: {
				Title: "모드 토글 및 삭제 방법",
				Great: "훌륭합니다! 이제 모드를 삭제하려면",
				OnTopRight: "우상단의",
				RClick: "모드에 오른쪽 클릭하여 켜기/끄기 전환",
			},
			p3: {
				Title: "모드 관리",
				Rename: "모드 이름을 다음으로 변경",
				ClickOn: "클릭",
				PImg: "미리보기 이미지 변경",
				Cat: "카테고리를 다음으로 설정",
			},
			p4: {
				Title1: "복원 및 설정 페이지",
				Msg: {
					0: "복원 또는 설정 페이지 열기",
					1: "훌륭합니다! 이제 복원 페이지를 여세요",
					10: "훌륭합니다! 이제 설정 페이지를 여세요",
					11: "---",
				},
				Title2: "온라인으로 이동",
				ClickAnywhere: "아무 곳이나 클릭하여 계속",
			},
			p5: {
				Title: "모드 탐색 및 설치",
				Switch: "온라인 모드로 전환",
				Browse: "Gamebanana에서 모드 탐색",
				Update: "모드 업데이트 및 설치",
			},
			p6: {
				Title: "모드 설치",
				Direct: "모드 폴더에 직접 다운로드",
				Unzip: "파일 자동 압축 해제",
				Preview: "미리보기가 다운로드됩니다",
			},
			p7: {
				Title: "링크에서 모드 보기",
				Copy: "Gamebanana에서 모드 링크 복사",
			},
			p8: {
				Title: "링크에서 모드 보기",
				Paste: "IMM 창 아무 곳에나 붙여넣기",
				Opens: "모드가 온라인 모드에서 열립니다",
			},
			p9: {
				Title: "튜토리얼 완료!",
				Again1: "다시 튜토리얼을 진행하려면",
				Again2: "왼쪽 상단의 앱 아이콘을 클릭하세요",
				More: "앞으로 더 많은 대화형 튜토리얼이 추가될 예정입니다. 기대해주세요!",
				End: "아무 곳이나 클릭하여 튜토리얼 종료",
			},
			Skip: "건너뛰기",
		},
	},
};
